### ISSUE TITLE
Confirming Board for MicroJoy

### ISSUE THREAD

**Issue by maurbeck** [menehune23/microjoy#2]
Hi there, I'd just like to confirm that the board on OSH park is the latest updated version from github.

https://oshpark.com/shared_projects/bY76fZP4

If so, I'll order them now ^_^ Thanks!

**Comment by menehune23** [comment]
Yep that's it!

Andrew

**Comment by maurbeck** [comment]
Thanks, I'll let you know how things go! I have all the additional parts coming in from Ali as well

**Comment by maurbeck** [comment]
Turns out the headers I bought are too small for the Microview. Any idea what the pin size is on it?

Free Shipping 10pcs 1x40 Pin 2.54 sing Round Female Pin Header connecto
 http://s.aliexpress.com/a6v63Ine 

Seem to be larger than 2.54. Also, from the picture you posted, it seems like the Microview pins were cut short. At least it seems as if they are much shorter than on my model.

But perhaps I'm misunderstanding your assembly instructions. I'm not familiar with what you're referring to with the fiber plugs that pop out of the headers in 1.a.

**Comment by menehune23** [comment]
Hi maurbeck,

I remember having a similar issue when trying to find headers. The MicroView pins are a bit wider than usual, so I don’t recommend using the standard headers that you posted a link for. According to https://www.sparkfun.com/products/12923#comment-5567f0fe757b7ff55a8b4567, where I first asked about it, they are square pins with a side length of 0.064mm, which gives a diagonal diameter of about 0.9051mm.

I highly recommend the pass-thru headers that I used (you can find the part number on my BOM, but the direct link to the data sheet is: https://www.mill-max.com/products/datasheet/sockets/834-43-008-10-001000 <https://www.mill-max.com/products/datasheet/sockets/834-43-008-10-001000>). These headers are different from usual headers in that they are essentially “bottomless”, allowing the MicroView pins to pass completely through the board if needed. The headers come pre-plugged with fiber on the bottom end so that solder doesn’t get into them when soldering to the PCB. The plugs will likely pop out the first time a pin goes through the header completely.

Regarding length, the MicroView pins may have changed in length since I first bought mine via Kickstarter, but I don’t believe I trimmed them.

Hope that helps!

**Comment by menehune23** [comment]
Closing, as original issue addressed
